

INTERFACE
SUBROUTINE TURB_VER1 (PTHLM, PDZZ, PRM, KKA,KKU,KKL,KRR, HTURBDIM, GUSERV)

IMPLICIT NONE

!
LOGICAL :: GUSERV    ! flag to use water vapor
CHARACTER*4 ::  HTURBDIM     
INTEGER :: KKA,KKU,KKL,KRR
REAL*8, DIMENSION(:,:,:) ::  PTHLM
REAL*8, DIMENSION(:,:,:) ::  PDZZ
REAL*8, DIMENSION(:,:,:,:) ::  PRM          
END SUBROUTINE

SUBROUTINE TURB_VER2 (PTHLM, PDZZ, PRM, KKA,KKU,KKL,KRR, HTURBDIM, GUSERV)

IMPLICIT NONE

!
LOGICAL :: GUSERV    ! flag to use water vapor
CHARACTER*4 ::  HTURBDIM     
INTEGER :: KKA,KKU,KKL,KRR
REAL*8, DIMENSION(:,:,:) ::  PTHLM
REAL*8, DIMENSION(:,:,:) ::  PDZZ
REAL*8, DIMENSION(:,:,:,:) ::  PRM          
END SUBROUTINE

END INTERFACE

LOGICAL :: GUSERV    ! flag to use water vapor
CHARACTER*4 ::  HTURBDIM     
INTEGER :: NPROMA, NFLEVG, KKA,KKU,KKL,KRR
REAL*8, ALLOCATABLE, DIMENSION(:,:,:) ::  PTHLM
REAL*8, ALLOCATABLE, DIMENSION(:,:,:) ::  PDZZ
REAL*8, ALLOCATABLE, DIMENSION(:,:,:,:) ::  PRM          

KKA = 1
KKU = 1
KKL = 1
KRR = 6

NPROMA = 32
NFLEVG = 50

ALLOCATE (PTHLM (NPROMA, 1, NFLEVG), PDZZ (NPROMA, 1, NFLEVG), PRM (NPROMA, 1, NFLEVG, KRR))

PRINT *, " TURB_VER1 " 
CALL TURB_VER1 (PTHLM, PDZZ, PRM, KKA,KKU,KKL,KRR, HTURBDIM, GUSERV)
PRINT *, " TURB_VER2 " 
CALL TURB_VER2 (PTHLM, PDZZ, PRM, KKA,KKU,KKL,KRR, HTURBDIM, GUSERV)


END
