MODULE MODE_PRANDTL
IMPLICIT NONE
CONTAINS
FUNCTION PHI3(PREDTH1,PREDR1,PRED2TH3,PRED2R3,PRED2THR3,HTURBDIM,OUSERV)
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PREDTH1
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PREDR1
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PRED2TH3
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PRED2R3
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PRED2THR3
  CHARACTER(len=4),       INTENT(IN) :: HTURBDIM  ! 1DIM or 3DIM turb. scheme
  LOGICAL,                INTENT(IN) :: OUSERV    ! flag to use vapor
  REAL*8, DIMENSION(SIZE(PREDTH1,1),SIZE(PREDTH1,2),SIZE(PREDTH1,3)) :: PHI3
END FUNCTION PHI3
FUNCTION PSI3(PREDR1,PREDTH1,PRED2R3,PRED2TH3,PRED2THR3,HTURBDIM,OUSERV)
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PREDTH1
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PREDR1
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PRED2TH3
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PRED2R3
  REAL*8, DIMENSION(:,:,:), INTENT(IN) :: PRED2THR3
  CHARACTER(len=4),       INTENT(IN) :: HTURBDIM  ! 1DIM or 3DIM turb. scheme
  LOGICAL,                INTENT(IN) :: OUSERV    ! flag to use vapor
  REAL*8, DIMENSION(SIZE(PREDTH1,1),SIZE(PREDTH1,2),SIZE(PREDTH1,3)) :: PSI3
!
END FUNCTION PSI3
END MODULE
