SUBROUTINE TURB_VER1 (PTHLM, PDZZ, PRM, KKA,KKU,KKL,KRR, HTURBDIM, GUSERV)

USE MODI_GRADIENT_M
USE MODE_PRANDTL
!
IMPLICIT NONE

!
LOGICAL :: GUSERV    ! flag to use water vapor
CHARACTER*4 ::  HTURBDIM     
INTEGER :: KKA,KKU,KKL,KRR
REAL*8, DIMENSION(:,:,:) ::  PTHLM
REAL*8, DIMENSION(:,:,:) ::  PDZZ
REAL*8, DIMENSION(:,:,:,:) ::  PRM          

REAL*8, DIMENSION(SIZE (PTHLM, 1), SIZE (PTHLM, 2), SIZE (PTHLM, 3)) &
  & ::  ZDTH_DZ, ZDR_DZ, ZPHI3, ZPSI3
REAL*8, DIMENSION(SIZE (PTHLM, 1), SIZE (PTHLM, 2), SIZE (PTHLM, 3)) &
  & ::  ZREDTH1, ZREDR1, ZRED2TH3, ZRED2R3, ZRED2THR3


ZDTH_DZ = GZ_M_W(KKA,KKU,KKL,PTHLM(:,:,:),PDZZ)
IF (KRR>0) THEN 
  ZDR_DZ  = GZ_M_W(KKA,KKU,KKL,PRM(:,:,:,1),PDZZ)
ENDIF

ZPHI3 = PHI3(ZREDTH1,ZREDR1,ZRED2TH3,ZRED2R3,ZRED2THR3,HTURBDIM,GUSERV)
IF(KRR/=0) THEN
  ZPSI3 = PSI3(ZREDR1,ZREDTH1,ZRED2R3,ZRED2TH3,ZRED2THR3,HTURBDIM,GUSERV)
ENDIF

END


